### ISSUE TITLE
How the orientation of "pose" works?

### ISSUE THREAD

**Issue by IanMin1022** [clearpathrobotics/vrpn_ros#11]
I succeeded to extract the data and everything seemed fine until I found out that the yaw of orientation works little bit weird.
So far what I found out is, the value of y(yaw) is sin of theta which is divided by 2 from the origin degree. This is okay, but when I flipped the object it went crazy. I kept trying to find a rule about how flipping affects y value whenever I flipped it, but, apparently, it seems like there is no rule. 
I just want to know how the orientation works, especially for y(yaw), and what the w is for.

**Comment by paulbovbel** [comment]
The orientation is a quaternion - see http://wiki.ros.org/Tutorials/Quaternions and ROS Answers if you have further questions.
