### ISSUE TITLE
Unable to locate package ros-kinetic-vrpn-client-ros

### ISSUE THREAD

**Issue by kumarrt** [clearpathrobotics/vrpn_ros#12]
I am using Ubuntu 16.04 and ROS Kinetic. When I try to run "**sudo apt-get install ros-kinetic-vrpn-client-ros**", I get the error "**unable to locate package**". I have also tried cloning from the git-repository but when I try to do catkin_make it fails and 
![vrpn_error](https://user-images.githubusercontent.com/38470089/39325413-1bfdd3ac-4960-11e8-95a9-8be434843b69.jpg)
I have also tried to run "**rosdep install --from-paths**" but it gives an error saying "**rosdep: error: no packages or stacks specified**"
How can I resolve this issue?

**Comment by sudosurf** [comment]
Hi Kumarrt, I just tried sudo apt-get install ros-kinetic-vrpn-client-ros on Ubuntu 16.04 and the installation worked no problem. All repositories up to date? already tried apt-get update and upgrade?

**Comment by kumarrt** [comment]
I tried the same things but for some reason it is not able to make it work. 

```
sudo apt-get install ros-kinetic-vrpn-client-ros
[sudo] password for uav_master: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-kinetic-vrpn-client-ros
```
Please suggest any other alternatives.

**Comment by sudosurf** [comment]
The debian package is out there, so the issue is on your machine. In my experience with these simple but confounding issues, its usually something very basic I overlooked (like I forgot to connect to wifi). If you've gone back to the basics and it isn't something you can fix, it might be worth doing a fresh ubuntu install.

**Comment by Amir-Omidfar** [comment]
I'm having the same issue? did u figure it out?

**Comment by SeungJunWoo** [comment]
I'm having the same issue did you figure it out?

**Comment by PedroDesRobots** [comment]
Maybe you have VRPN already install but `find_package` didn't find VRPN cmake file. 

> Could not find a package configuration file provided by "VRPN"

 

You should check inside : `/usr/share/cmake/Modules` if `FindVRPN.cmake` exists. If not
you just have to create it and copy the file from vrpn source ([link](https://github.com/vrpn/vrpn/blob/master/cmake/FindVRPN.cmake))

After that, I got the same error but for `quatlib`, so I just added  `Findquatlib.cmake` ([link](https://github.com/vrpn/vrpn/blob/master/cmake/Findquatlib.cmake))

If you don't have VRPM install yet :
downloaded a version of VRPN and unzipped it, [link](https://github.com/vrpn/vrpn/releases)
tar xyz vrpn-07.33.tar.gz (adapt name to your vrpn version)
if you use CMake just go inidse your vrpn folder
```cd vrpn
mkdir build
cmake ..
make -j4
make install
```
then, run `catkin build` or `catkin_make`

**Comment by paulbovbel** [comment]
the VRPN dependency is apt packaged as `ros-<distro>-vrpn`, I would not recommend installing it from source for any future spelunkers.
