### ISSUE TITLE
No node publishing postion data

### ISSUE THREAD

**Issue by m1577** [clearpathrobotics/vrpn_ros#7]
I want to send the data of posision of the cameras optitrack (windows pc) to ros (ubuntu pc). I was reading many forums and decided to choose the method vrpn_client_ros.

In Motive I have the vrpn broadcast option with ip (239.255.42.99) and a port: 3883. I made a LAN with a router where the windows pc has an ip (192.168.1.2) and the Ubuntu pc has an ip (192.168.1.1).

When I run the launch file (roslaunch vrpn_client_ros sample.launch server: = "239.255.42.99") on a terminal, I get the answers: "Connecting to VRPN server at 239.255.42.99" and "Connection established".

My problem is that the topics published do not appear, and therefore I can not get the position data in ros.

How can I solve this problem?

Do I have to modify the launch file?

Reagards!!

**Comment by kcheung01** [comment]
You may need to declare the port for the vrpn server...

i.e. something like 
roslaunch vrpn_client_ros sample.launch server:=239.255.42.99:3883

Also, do you have the optitrack software that has the VRPN backend running on the windows PC?

**Comment by paulbovbel** [comment]
@m1577, this isn't exactly a bug, so in the future, please post on ROS Answers.

See https://github.com/clearpathrobotics/vrpn_client_ros/blob/6249db9040d6121301891aaf3f88a2113c3879c6/launch/sample.launch, 3883 is the default port.

Topics are published automatically for any registered trackers. If they are not showing up, you should use the vrpn CLI tools to make sure your client machine can talk to your server properly, as shown on the wiki.

**Comment by neudinglei** [comment]
@m1577 
Hello! m1577.Can you explain what the three ip respectively represent? Are you now communicating successfully? Thank you

**Comment by neudinglei** [comment]
@m1577 @kcheung01 @paulbovbel 
The system is optitrack. Now  the ros package is vrpn_client_ros.When I run the launch file (roslaunch crazyflie_demo hover_vrpn.launch) on a terminal, it did not suggest any errors.But, it can not get the data from optitrack(using motive on windows PC),that is to say that the actual location of the crazyflie can not be obtained.Can you provide a solution?
In the hover_vrpn.launch, The parameters are set as follows；
arg name="ip" default="192.168.56.1" />（ip of windows PC）
arg name="port" default="3883" />
arg name="uri" default="radio://0/80/250K/E7E7E7E7E7" />
arg name="frame" default="/world>
Is there a problem with parameter settings?thank you!

**Comment by neudinglei** [comment]
Hello @m1577 @kcheung01 @paulbovbel @mikeodr @efernandez 
We are using  motive now. Now I'm having trouble communicating with another unbantu computer via VRPN, and now I can not read rigid data on the ubuntu computer. Can you give me a solution?

**Comment by m1577** [comment]
Hello @neudinglei The problem I had is that I put the ip that has example in motive, The ip that you have to put is the one of your windows PC, do not put the iP that comes to you in motive. Regards!!
