### ISSUE TITLE
streaming position of single marker

### ISSUE THREAD

**Issue by ghanimmukhtar** [clearpathrobotics/vrpn_ros#9]
Hi There,

Is it possible to stream the position (no orientation) of single markers from Motive, via this package? If so what do I need to change to achieve that?

Cheers!

**Comment by paulbovbel** [comment]
No. It's possible to subscribe to a single marker, but you'll still get all the data that's available to VRPN. Pull requests to change that are welcome.

**Comment by fabrizioschiano** [comment]
I know it is an old question but the answer is not entirely clear to me. 

Is it possible to subscribe to a single marker or not with the current version of this package? 

If yes, how would you do it?
